# List of profiles
- name: XMA
  link: https://www.xivmodarchive.com/user/111283
  frontpage: true

- name: TGD
  link: https://www.glamourdresser.com/author/catcraft
  frontpage:

- name: Patreon
  link: https://www.patreon.com/catcraftFFXIV
  frontpage: true

- name: Boosty
  link: https://boosty.to/miaumori
  frontpage:

- name: Shop
  link: https://www.patreon.com/catcraftffxiv/shop
  frontpage:

- name: Shop (no VAT)
  link: https://hipolink.me/pomigrein/products
  frontpage:

- name: Bsky
  link: https://bsky.app/profile/catcraftxiv.bsky.social
  frontpage:

- name: Twitter
  link: https://x.com/catcraftxiv
  frontpage: true
  
- name: Discord
  link: https://discord.gg/yPbUXazxQ3
  frontpage: true

- name: Ko-fi
  link: https://ko-fi.com/catcraft
  frontpage:

- name: Hipolink
  link: https://hipolink.me/pomigrein
  frontpage:

- name: Mod Rules
  link: https://catcraftxiv.github.io/web/rules
  frontpage:

- name: Evie boosty
  link: https://boosty.to/evilieda
  frontpage:
